buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

providers = ["...", "python"]

# [phases.setup]
# nixPkgs = ["...", "gnupg"]

[phases.gdal]
dependsOn = ['python:install']
cmds = ['wget https://repo.anaconda.com/miniconda/Miniconda3-py39_23.5.1-0-Linux-x86_64.sh',
        'bash Miniconda3-py39_23.5.1-0-Linux-x86_64.sh -b',
        'source /root/miniconda3/bin/activate',
        'conda init',
        'conda list']