buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

providers = ["...", "python"]

[phases.setup]
# cmds = ['...', 'wget https://repo.anaconda.com/miniconda/Miniconda3-py39_23.5.1-0-Linux-x86_64.sh',
#         'bash Miniconda3-py39_23.5.1-0-Linux-x86_64.sh -b']
#nixPkgs = ["...", "gdalMinimal"]
aptPkgs = ["...", "python3-gdal"]

[phases.install]
# cmds = ['...', 'conda install gdal']

# [phases.conda1]
# dependsOn = ['python:install']
# cmds = ['rm Miniconda3-py39_23.5.1-0-Linux-x86_64.sh',
#         'ls -alsht /root/miniconda3/bin/']

# [phases.conda2]
# dependsOn = ['conda1']
# cmds = ['export PATH=$PATH:/root/miniconda3/bin/:/root/miniconda3/condabin/',
#         'source /root/miniconda3/bin/activate',
#         'conda init']

# [phases.gdal]
# dependsOn = ['conda2']
# cmds = ['conda create -n gdal python=3.9',
#         'conda activate gdal',
#         'conda install gdal']

# [phases.gdal_verify]
# dependsOn = ['gdal']
# cmds = ['gdal-config --version']