providers = ["...", "python"]

[phases.setup]
aptPkgs = ["...", "libgdal-dev=3.6.2"]

[phases.gdal]
dependsOn = ['python:install']
cmds = ["pip install --upgrade pip", "pip install wheel==0.41.0", "pip install gdal==3.6.2"]