buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

providers = ["...", "python"]

[phases.setup]
cmds = ['...', 'wget https://repo.anaconda.com/miniconda/Miniconda3-py39_23.5.1-0-Linux-x86_64.sh',
        'bash Miniconda3-py39_23.5.1-0-Linux-x86_64.sh -b']

[phases.conda1]
dependsOn = ['python:install']
cmds = ['rm Miniconda3-py39_23.5.1-0-Linux-x86_64.sh',
        'ls -alsht /root/miniconda3/bin/']

[phases.conda2]
dependsOn = ['conda1']
cmds = ['source /root/miniconda3/bin/activate',
        '/root/miniconda3/bin/conda init',
        '/root/miniconda3/bin/conda list']

[phases.gdal]
dependsOn = ['conda2']
cmds = ['/root/miniconda3/bin/conda install gdal']

[phases.gdal_verify]
dependsOn = ['gdal']
cmds = ['gdal-config --version']