const CHUNK_PUBLIC_PATH = "server/app/page.js";
const runtime = require("../chunks/ssr/[turbopack]_runtime.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_523063._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_flowbite-react_dist_esm_0627f7._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_react-icons_f47472._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_tailwind-merge_dist_bundle-mjs_mjs_6bc68a._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_7c093e._.js");
runtime.loadChunk("server/chunks/ssr/_b3a278._.js");
runtime.getOrInstantiateRuntimeModule("[project]/.next-internal/server/app/page/actions.js [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH);
module.exports = runtime.getOrInstantiateRuntimeModule("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { COMPONENT_0 => \"[project]/app/layout.jsx [app-rsc] (ecmascript, Next.js server component)\", COMPONENT_1 => \"[project]/app/loading.js [app-rsc] (ecmascript, Next.js server component)\", COMPONENT_2 => \"[project]/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)\", COMPONENT_3 => \"[project]/app/page.jsx [app-rsc] (ecmascript, Next.js server component)\" } [app-rsc] (ecmascript) <facade>", CHUNK_PUBLIC_PATH).exports;
